function fx_phys = fx_fun(in1,in2)
%FX_FUN
%    FX_PHYS = FX_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    11-Apr-2025 10:47:38

dphi = in1(10,:);
dpsi = in1(12,:);
dtheta = in1(11,:);
dx = in1(4,:);
dy = in1(5,:);
dz = in1(6,:);
phi = in1(7,:);
theta = in1(8,:);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = t2.^2;
t7 = t3.^2;
t8 = t4.^2;
t9 = t5.^2;
t10 = 1.0./t3;
t11 = t6+t8;
t12 = 1.0./t11;
fx_phys = [dx;dy;dz;0.0;0.0;((t6.*t7.*4.9e+1+t6.*t9.*4.9e+1+t7.*t8.*4.9e+1+t8.*t9.*4.9e+1).*(-1.0./5.0))./(t6.*t7+t6.*t9+t7.*t8+t8.*t9);dphi;dtheta;dpsi;t10.*t12.*(dphi.*dtheta.*t5.*t6+dphi.*dtheta.*t5.*t8+dpsi.*dtheta.*t6.*t7+dpsi.*dtheta.*t6.*t9+dpsi.*dtheta.*t7.*t8+dpsi.*dtheta.*t8.*t9);-t12.*(dphi.*dpsi.*t3.*t6+dphi.*dpsi.*t3.*t8);t10.*t12.*(dphi.*dtheta.*t6+dphi.*dtheta.*t8+dpsi.*dtheta.*t5.*t6+dpsi.*dtheta.*t5.*t8)];
end
